from itertools import chain

LINE_LIMIT = 8

def print_fem(input_data, path_fem_new, sectioned_variable):
    with open(path_fem_new, 'w') as file:

        file.write('$$\n')
        file.write('$$ Optistruct Input Deck Generated by Python Version\n')
        file.write('$$ Generated using HyperMesh-Optistruct Template Version 2023.1.0.22-53972\n')
        file.write('$$\n')
        file.write('$$   Template:  optistruct\n')
        file.write('$$\n')
        file.write('$$\n')
        file.write('$$ optistruct\n')
        file.write('$\n')

        try:
            for line in input_data.get('IO', []):
                file.write(f"{line}\n")
        except Exception:
            pass

        file.write('$$------------------------------------------------------------------------------$\n')
        file.write('$$                      Case Control Cards                                      $\n')
        file.write('$$------------------------------------------------------------------------------$\n')

        try:
            file.write('$$\n')
            file.write('$$  OBJECTIVES Data\n')
            file.write('$$\n')
            print_objectives_data_hypermesh(input_data, file)
        except Exception:
            pass

        file.write('$\n\n$$$$$$ SORTED ECHO OF THE INPUT DECK $$$$$$\n\n\n$\n')

        try:
            file.write('$ subcase cards\n')
            print_out_subcase_data_hypermesh(input_data, file)
        except Exception:
            pass

        try:
            names_bulk = list(input_data['BULK'].keys())
            if sectioned_variable in (0, 1):
                file.write('BEGIN BULK\n$\n')

            empty_text = '+'.ljust(LINE_LIMIT)
            for name in names_bulk:
                file.write(f'$$\n$$  {name} Data\n$$\n')

                if name == 'CONTROL_CARDS':
                    for line in input_data['BULK'][name]:
                        file.write(f'{line}\n')
                else:
                    print_out_bulk_data(input_data, name, empty_text, LINE_LIMIT, file)

            if sectioned_variable in (0, 2):
                file.write('$\nENDDATA\n$\n')
        except Exception:
            pass


def print_out_subcase_data_hypermesh(input_data, file):
    for idx, subcase in enumerate(input_data.get('SUBCASE', []), start=1):
        if not all(value == '' for value in subcase.values()):
            file.write('$\n')
            file.write(f'  SUBCASE = {idx}\n')
            for key, value in subcase.items():
                if value != '':
                    key_upper = key.upper()
                    value_str = str(value).strip()
                    if value_str.replace('.', '', 1).isdigit():
                        value_str = value_str.rjust(9)
                    file.write(f'  {key_upper:<9}= {value_str}\n')
            file.write('$\n')


def print_objectives_data_hypermesh(input_data, file):
    objectives = input_data.get('OBJECTIVES', {})
    for key, value in objectives.items():
        key_upper = key.upper()
        if value:
            row = value[0]
            if key_upper == 'DESOBJ':
                flag = row[0]
                val = row[1]
                val_str = str(val) if not isinstance(val, (int, float)) else str(int(val))
                file.write(f'DESOBJ({flag})={val_str}\n')
            elif key_upper == 'DESGLB':
                val = row
                val_str = str(val) if not isinstance(val, (int, float)) else str(int(val)).rjust(9)
                file.write(f' DESGLB  = {val_str}\n')


def append_card_info(cell_in, empty_text, card_text):
    """
    Mimics the MATLAB append_card_info function.
    Prepends the card_text to the first row, and empty_text (usually '+') to subsequent rows.
    """
    rows = len(cell_in)

    out = []
    new_cells = [card_text] + [empty_text] * (rows - 1)
    for i in range(rows):
        out.append([new_cells[i]] + cell_in[i])

    return out


def print_out_bulk_data(input_data, current_name, empty_text, line_limit, file):
    """
    Converts and writes bulk data to a .fem/.bdf file.

    input_data: dict structure like {'BULK': {'GRID': [[...], [...]], ...}}
    current_name: the current bulk card (e.g. 'GRID')
    empty_text: continuation character (e.g. '+') padded to line_limit
    line_limit: maximum length of any field (typically 8 for short format)
    file: open file object to write to
    """
    cell_block = input_data['BULK'][current_name]
    card_text = current_name.ljust(line_limit)[:line_limit]

    padded_cells = []
    text_cols = []

    for block in cell_block:
        padded_rows = []

        for row in block:
            padded_row = []
            for cell in row:
                cell_str = str(cell).ljust(line_limit)[:line_limit]
                padded_row.append(cell_str)
            padded_rows.append(padded_row)

        # Wrap with card label / continuation symbols
        wrapped_rows = append_card_info(padded_rows, empty_text, card_text)
        for wrapped_row in wrapped_rows:
            padded_cells.append(wrapped_row)
            text_cols.append(len(wrapped_row))

    # Ensure all lines have same number of columns (use shortest)
    min_cols = min(text_cols)
    equalized_cells = [''.join(row[:min_cols]) for row in padded_cells]

    for line in equalized_cells:
        file.write(f"{line.rstrip()}\n")
